package heero.mc.mod.wakcraft.network;

public enum GuiId {
    UNKNOWN,

    CHARACTERISTIC,
    HAVEN_BAG_CHEST_ADVENTURER,
    HAVEN_BAG_CHEST_COLLECTOR,
    HAVEN_BAG_CHEST_EMERALD,
    HAVEN_BAG_CHEST_GOLDEN,
    HAVEN_BAG_CHEST_KIT,
    HAVEN_BAG_CHEST_NORMAL,
    HAVEN_BAG_CHEST_SMALL,
    HAVEN_BAG_VISITORS,
    HAVEN_GEM_WORKBENCH,
    INVENTORY,
    NPC_GIVE,
    PROFESSION,
    QUEST,
    SPELLS,
    WORKBENCH,
    ZAAPS
}
