package heero.mc.mod.wakcraft.network;

public enum GuiId {
    UNKNOW,

    ABILITIES,
    INVENTORY,
    HAVEN_BAG_CHEST_NORMAL,
    HAVEN_BAG_CHEST_SMALL,
    HAVEN_BAG_CHEST_ADVENTURER,
    HAVEN_BAG_CHEST_KIT,
    HAVEN_BAG_CHEST_COLLECTOR,
    HAVEN_BAG_CHEST_GOLDEN,
    HAVEN_BAG_CHEST_EMERALD,
    HAVEN_BAG_VISITORS,
    HAVEN_GEM_WORKBENCH,
    WORKBENCH,
    PROFESSION,
    SPELLS,
    ZAAPS
}
