// Date: 05/04/2014 00:36:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package heero.wakcraft.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGobbette extends ModelGobball {
	ModelRenderer bunchesLeft1;
	ModelRenderer bunchesRight1;
	ModelRenderer bunchesRigh2;
	ModelRenderer bunchesLeft2;

	public ModelGobbette() {
		super();
		
		bunchesLeft1 = new ModelRenderer(this, 64, 0);
		bunchesLeft1.addBox(-3F, 0F, 0F, 4, 5, 2);
		bunchesLeft1.setRotationPoint(-4F, 3F, -4F);
		bunchesLeft1.setTextureSize(128, 64);
		bunchesLeft1.mirror = false;
		setRotation(bunchesLeft1, 0F, 0F, -0.2617994F);
		
		bunchesRight1 = new ModelRenderer(this, 64, 0);
		bunchesRight1.addBox(0F, 0F, 0F, 4, 5, 2);
		bunchesRight1.setRotationPoint(3F, 2.8F, -4F);
		bunchesRight1.setTextureSize(128, 64);
		bunchesRight1.mirror = true;
		setRotation(bunchesRight1, 0F, 0F, 0.2617994F);
		
		bunchesRigh2 = new ModelRenderer(this, 64, 7);
		bunchesRigh2.addBox(0F, 0F, 0F, 4, 5, 2);
		bunchesRigh2.setRotationPoint(6F, 3.7F, -5F);
		bunchesRigh2.setTextureSize(128, 64);
		bunchesRigh2.mirror = false;
		setRotation(bunchesRigh2, 0.2617994F, -1.570796F, 0F);
		
		bunchesLeft2 = new ModelRenderer(this, 64, 7);
		bunchesLeft2.addBox(0F, 0F, 0F, 4, 5, 2);
		bunchesLeft2.setRotationPoint(-6F, 3.6F, -1F);
		bunchesLeft2.setTextureSize(128, 64);
		bunchesLeft2.mirror = true;
		setRotation(bunchesLeft2, 0.2617994F, 1.570796F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);

		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		bunchesLeft1.render(f5);
		bunchesRight1.render(f5);
		bunchesRigh2.render(f5);
		bunchesLeft2.render(f5);
	}
}
