// Date: 08/04/2014 14:26:08
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package heero.mc.mod.wakcraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDragoexpress extends ModelBase {
	// fields
	ModelRenderer Chariot;
	ModelRenderer Roue_BL;
	ModelRenderer Roue_FL;
	ModelRenderer Roue_FR;
	ModelRenderer Roue_BR;
	ModelRenderer Poutre_L;
	ModelRenderer Poutre_R;

	public ModelDragoexpress() {
		textureWidth = 128;
		textureHeight = 256;

		Chariot = new ModelRenderer(this, 0, 0);
		Chariot.addBox(0F, 0F, 0F, 18, 24, 22);
		Chariot.setRotationPoint(15F, 11F, 32F);
		Chariot.setTextureSize(128, 256);
		Chariot.mirror = true;
		setRotation(Chariot, 0F, 0F, 0F);
		Roue_BL = new ModelRenderer(this, 0, 80);
		Roue_BL.addBox(0F, 0F, 0F, 2, 10, 10);
		Roue_BL.setRotationPoint(33F, 30F, 45F);
		Roue_BL.setTextureSize(128, 256);
		Roue_BL.mirror = true;
		setRotation(Roue_BL, 0F, 0F, 0F);
		Roue_FL = new ModelRenderer(this, 0, 80);
		Roue_FL.addBox(0F, 0F, 0F, 2, 10, 10);
		Roue_FL.setRotationPoint(33F, 30F, 31F);
		Roue_FL.setTextureSize(128, 256);
		Roue_FL.mirror = true;
		setRotation(Roue_FL, 0F, 0F, 0F);
		Roue_FR = new ModelRenderer(this, 0, 80);
		Roue_FR.addBox(0F, 0F, 0F, 2, 10, 10);
		Roue_FR.setRotationPoint(13F, 30F, 31F);
		Roue_FR.setTextureSize(128, 256);
		Roue_FR.mirror = true;
		setRotation(Roue_FR, 0F, 0F, 0F);
		Roue_BR = new ModelRenderer(this, 0, 80);
		Roue_BR.addBox(0F, 0F, 0F, 2, 10, 10);
		Roue_BR.setRotationPoint(13F, 30F, 45F);
		Roue_BR.setTextureSize(128, 256);
		Roue_BR.mirror = true;
		setRotation(Roue_BR, 0F, 0F, 0F);
		Poutre_L = new ModelRenderer(this, 0, 50);
		Poutre_L.addBox(0F, 0F, -14F, 3, 3, 24);
		Poutre_L.setRotationPoint(27F, 35F, 32F);
		Poutre_L.setTextureSize(128, 256);
		Poutre_L.mirror = true;
		setRotation(Poutre_L, 0.1570796F, 0F, 0F);
		Poutre_R = new ModelRenderer(this, 0, 50);
		Poutre_R.addBox(0F, 0F, -14F, 3, 3, 24);
		Poutre_R.setRotationPoint(18F, 35F, 32F);
		Poutre_R.setTextureSize(128, 256);
		Poutre_R.mirror = true;
		setRotation(Poutre_R, 0.1570796F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Chariot.render(f5);
		Roue_BL.render(f5);
		Roue_FL.render(f5);
		Roue_FR.render(f5);
		Roue_BR.render(f5);
		Poutre_L.render(f5);
		Poutre_R.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
