// Date: 03/07/2014 19:53:18
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package heero.mc.mod.wakcraft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBowMeow extends ModelBase
{
  //fields
    ModelRenderer Tete;
    ModelRenderer Corps;
    ModelRenderer Queue;
    ModelRenderer OreilleGauche;
    ModelRenderer BoutOreilleGauche;
    ModelRenderer OreilleDroite;
    ModelRenderer BoutOreilleDroite;
    ModelRenderer Meche;
    ModelRenderer MechePic;
    ModelRenderer Moustache;
    ModelRenderer PatteGauche;
    ModelRenderer PatteDroite;
    ModelRenderer PatteDroiteBas;
    ModelRenderer PatteGaucheBas;
  
  public ModelBowMeow()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Tete = new ModelRenderer(this, 20, 15);
      Tete.addBox(0F, 0F, 0F, 6, 6, 6);
      Tete.setRotationPoint(0F, 15F, -4F);
      Tete.setTextureSize(64, 64);
      Tete.mirror = true;
      setRotation(Tete, 0F, 0F, 0F);
      
      Corps = new ModelRenderer(this, 24, 31);
      Corps.addBox(0F, 0F, 0F, 4, 4, 4);
      Corps.setRotationPoint(1F, 19F, 0F);
      Corps.setTextureSize(64, 64);
      Corps.mirror = true;
      setRotation(Corps, 0F, 0F, 0F);
      
      Queue = new ModelRenderer(this, 26, 40);
      Queue.addBox(0F, 0F, 0F, 1, 1, 5);
      Queue.setRotationPoint(2F, 20F, 4F);
      Queue.setTextureSize(64, 64);
      Queue.mirror = true;
      setRotation(Queue, 0F, 0F, 0F);
      
      OreilleGauche = new ModelRenderer(this, 21, 9);
      OreilleGauche.addBox(0F, 0F, 0F, 1, 3, 2);
      OreilleGauche.setRotationPoint(5F, 13F, -1F);
      OreilleGauche.setTextureSize(64, 64);
      OreilleGauche.mirror = true;
      setRotation(OreilleGauche, -0.4363323F, 1.570796F, 0F);
      
      BoutOreilleGauche = new ModelRenderer(this, 22, 7);
      BoutOreilleGauche.addBox(0F, 1F, -1F, 1, 1, 1);
      BoutOreilleGauche.setRotationPoint(6F, 12F, -1F);
      BoutOreilleGauche.setTextureSize(64, 64);
      BoutOreilleGauche.mirror = true;
      setRotation(BoutOreilleGauche, 0.2328827F, 1.570796F, 0F);
      
      OreilleDroite = new ModelRenderer(this, 37, 9);
      OreilleDroite.addBox(0F, 0F, 0F, 1, 3, 2);
      OreilleDroite.setRotationPoint(-1F, 14F, -1F);
      OreilleDroite.setTextureSize(64, 64);
      OreilleDroite.mirror = true;
      setRotation(OreilleDroite, 0.4363323F, 1.570796F, 0F);
      
      BoutOreilleDroite = new ModelRenderer(this, 38, 7);
      BoutOreilleDroite.addBox(0F, 0F, -1F, 1, 1, 1);
      BoutOreilleDroite.setRotationPoint(0F, 14F, -1F);
      BoutOreilleDroite.setTextureSize(64, 64);
      BoutOreilleDroite.mirror = true;
      setRotation(BoutOreilleDroite, -2.054634F, 1.570796F, 0F);
      
      Meche = new ModelRenderer(this, 30, 11);
      Meche.addBox(0F, 0F, 0F, 1, 2, 1);
      Meche.setRotationPoint(3F, 13F, -2F);
      Meche.setTextureSize(64, 64);
      Meche.mirror = true;
      setRotation(Meche, 0F, 0F, 0F);
      
      MechePic = new ModelRenderer(this, 30, 8);
      MechePic.addBox(0F, 0F, 0F, 1, 1, 1);
      MechePic.setRotationPoint(4F, 12F, -2F);
      MechePic.setTextureSize(64, 64);
      MechePic.mirror = true;
      setRotation(MechePic, 0F, 0F, 0.7853982F);
      
      Moustache = new ModelRenderer(this, 23, 28);
      Moustache.addBox(0F, 0F, 0F, 8, 1, 1);
      Moustache.setRotationPoint(-1F, 19F, -4F);
      Moustache.setTextureSize(64, 64);
      Moustache.mirror = true;
      setRotation(Moustache, 0F, 0F, 0F);
      
      PatteGauche = new ModelRenderer(this, 19, 31);
      PatteGauche.addBox(0F, 0F, 0F, 1, 1, 1);
      PatteGauche.setRotationPoint(4F, 23F, 3F);
      PatteGauche.setTextureSize(64, 64);
      PatteGauche.mirror = true;
      setRotation(PatteGauche, 0F, 0F, 0F);
      
      PatteDroite = new ModelRenderer(this, 41, 31);
      PatteDroite.addBox(0F, 0F, 0F, 1, 1, 1);
      PatteDroite.setRotationPoint(1F, 23F, 3F);
      PatteDroite.setTextureSize(64, 64);
      PatteDroite.mirror = true;
      setRotation(PatteDroite, 0F, 0F, 0F);
      
      PatteDroiteBas = new ModelRenderer(this, 41, 36);
      PatteDroiteBas.addBox(0F, 0F, 0F, 1, 1, 1);
      PatteDroiteBas.setRotationPoint(1F, 23F, 0F);
      PatteDroiteBas.setTextureSize(64, 64);
      PatteDroiteBas.mirror = true;
      setRotation(PatteDroiteBas, 0F, 0F, 0F);
      
      PatteGaucheBas = new ModelRenderer(this, 19, 37);
      PatteGaucheBas.addBox(0F, 0F, 0F, 1, 1, 1);
      PatteGaucheBas.setRotationPoint(4F, 23F, 0F);
      PatteGaucheBas.setTextureSize(64, 64);
      PatteGaucheBas.mirror = true;
      setRotation(PatteGaucheBas, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Tete.render(f5);
    Corps.render(f5);
    Queue.render(f5);
    OreilleGauche.render(f5);
    BoutOreilleGauche.render(f5);
    OreilleDroite.render(f5);
    BoutOreilleDroite.render(f5);
    Meche.render(f5);
    MechePic.render(f5);
    Moustache.render(f5);
    PatteGauche.render(f5);
    PatteDroite.render(f5);
    PatteDroiteBas.render(f5);
    PatteGaucheBas.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);	
	this.PatteDroite.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	this.PatteDroiteBas.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;
	this.PatteGauche.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;
	this.PatteGaucheBas.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;

  }

}
