// Date: 05/04/2014 22:28:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package heero.wakcraft.client.model;

import heero.wakcraft.entity.monster.Bouftou;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBouftouCG extends ModelGenericBouftou {
	// fields
	ModelRenderer hornL1;
	ModelRenderer hornL2;
	ModelRenderer hornL3;
	ModelRenderer hornR1;
	ModelRenderer hornR2;
	ModelRenderer hornR3;
	ModelRenderer tail1;
	ModelRenderer Shape1;

	public ModelBouftouCG() {
		hornL1 = new ModelRenderer(this, 24, 30);
		hornL1.addBox(0F, 0F, 0F, 4, 4, 6);
		hornL1.setRotationPoint(-12F, 7F, -8F);
		hornL1.setTextureSize(128, 64);
		hornL1.mirror = true;
		setRotation(hornL1, -0.3490659F, 0F, 0F);
		
		hornL2 = new ModelRenderer(this, 10, 30);
		hornL2.addBox(0F, 0F, 0F, 3, 3, 4);
		hornL2.setRotationPoint(-11.5F, 5.5F, -10F);
		hornL2.setTextureSize(128, 64);
		hornL2.mirror = true;
		setRotation(hornL2, -0.6981317F, 0F, 0F);
		
		hornL3 = new ModelRenderer(this, 0, 30);
		hornL3.addBox(0F, 0F, 0F, 2, 2, 3);
		hornL3.setRotationPoint(-11F, 4F, -12F);
		hornL3.setTextureSize(128, 64);
		hornL3.mirror = true;
		setRotation(hornL3, -0.8726646F, 0F, 0F);
		
		hornR1 = new ModelRenderer(this, 24, 30);
		hornR1.addBox(0F, 0F, 0F, 4, 4, 6);
		hornR1.setRotationPoint(8F, 7F, -8F);
		hornR1.setTextureSize(128, 64);
		hornR1.mirror = true;
		setRotation(hornR1, -0.3490659F, 0F, 0F);
		
		hornR2 = new ModelRenderer(this, 10, 30);
		hornR2.addBox(0F, 0F, 0F, 3, 3, 4);
		hornR2.setRotationPoint(8.5F, 5.5F, -10F);
		hornR2.setTextureSize(128, 64);
		hornR2.mirror = true;
		setRotation(hornR2, -0.6981317F, 0F, 0F);
		
		hornL3 = new ModelRenderer(this, 0, 30);
		hornL3.addBox(0F, 0F, 0F, 2, 2, 3);
		hornL3.setRotationPoint(9F, 4F, -12F);
		hornL3.setTextureSize(128, 64);
		hornL3.mirror = true;
		setRotation(hornL3, -0.8726646F, 0F, 0F);
		
		tail1 = new ModelRenderer(this, 44, 30);
		tail1.addBox(0F, 0F, 0F, 1, 9, 1);
		tail1.setRotationPoint(-0.5F, 3F, 10F);
		tail1.setTextureSize(128, 64);
		tail1.mirror = true;
		setRotation(tail1, -0.3490659F, 0F, 0F);
		
		Shape1 = new ModelRenderer(this, 48, 30);
		Shape1.addBox(0F, 0F, 0F, 3, 3, 3);
		Shape1.setRotationPoint(-1.5F, 1F, 9F);
		Shape1.setTextureSize(128, 64);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		hornL1.render(f5);
		hornL2.render(f5);
		hornL3.render(f5);
		hornR1.render(f5);
		hornR2.render(f5);
		hornL3.render(f5);
		tail1.render(f5);
		Shape1.render(f5);
	}
}
